/**
 * TaskWriter — Criação e transição de tarefas (gm_tasks) via RPCs do Core.
 */

import { dockerCoreClient } from "../docker-core/connection";

/**
 * Abre tarefa (OPEN → ACKNOWLEDGED). RPC start_task.
 */
export async function acknowledgeTask(taskId: string): Promise<void> {
  const { error } = await dockerCoreClient.rpc("start_task", {
    p_task_id: taskId,
    p_actor_id: null,
    p_restaurant_id: null,
  });
  if (error) throw new Error(error.message ?? "Falha ao iniciar tarefa");
}

/**
 * Conclui tarefa (OPEN/ACKNOWLEDGED → RESOLVED). RPC complete_task.
 */
export async function resolveTask(taskId: string): Promise<void> {
  const { error } = await dockerCoreClient.rpc("complete_task", {
    p_task_id: taskId,
    p_actor_id: null,
    p_restaurant_id: null,
  });
  if (error) throw new Error(error.message ?? "Falha ao concluir tarefa");
}

/**
 * Rejeita/descarta tarefa. RPC reject_task.
 */
export async function dismissTask(
  taskId: string,
  reason?: string | null
): Promise<void> {
  const { error } = await dockerCoreClient.rpc("reject_task", {
    p_task_id: taskId,
    p_reason: reason ?? null,
    p_actor_id: null,
    p_restaurant_id: null,
  });
  if (error) throw new Error(error.message ?? "Falha ao rejeitar tarefa");
}

/**
 * Assume + Start a task (moves to IN_PROGRESS via direct update).
 * Used when an operator clicks "Assumir" — takes ownership and begins work.
 */
export async function assumeTask(
  taskId: string,
  assigneeName?: string | null,
): Promise<void> {
  const updates: Record<string, unknown> = {
    status: "IN_PROGRESS",
    acknowledged_at: new Date().toISOString(),
  };
  if (assigneeName) {
    updates.assigned_name = assigneeName;
  }
  const { error } = await dockerCoreClient
    .from("gm_tasks")
    .update(updates)
    .eq("id", taskId);
  if (error) throw new Error(error.message ?? "Falha ao assumir tarefa");
}

/**
 * Inicia tarefa (OPEN → ACKNOWLEDGED). RPC start_task.
 */
export async function startTaskRpc(
  taskId: string,
  _userId: string | null,
  restaurantId: string
): Promise<void> {
  await acknowledgeTask(taskId);
}

/**
 * Conclui tarefa. RPC complete_task.
 */
export async function completeTaskRpc(
  taskId: string,
  _userId: string | null,
  restaurantId: string
): Promise<void> {
  await resolveTask(taskId);
}

/**
 * Rejeita tarefa. RPC reject_task.
 */
export async function rejectTaskRpc(
  taskId: string,
  _userId: string | null,
  restaurantId: string,
  reason?: string | null
): Promise<void> {
  await dismissTask(taskId, reason);
}

export interface CreateTaskRpcParams {
  restaurantId: string;
  taskType: string;
  message: string;
  priority?: string;
  station?: string | null;
  orderId?: string | null;
  orderItemId?: string | null;
  context?: Record<string, unknown>;
  autoGenerated?: boolean;
}

/**
 * Cria tarefa. RPC create_task.
 */
export async function createTaskRpc(params: CreateTaskRpcParams): Promise<string> {
  const { data, error } = await dockerCoreClient.rpc("create_task", {
    p_restaurant_id: params.restaurantId,
    p_task_type: params.taskType,
    p_message: params.message,
    p_station: params.station ?? null,
    p_priority: params.priority ?? "MEDIA",
    p_order_id: params.orderId ?? null,
    p_order_item_id: params.orderItemId ?? null,
    p_context: params.context ?? {},
    p_auto_generated: params.autoGenerated ?? false,
  });
  if (error) throw new Error(error.message ?? "Falha ao criar tarefa");
  const id = data as string;
  if (!id) throw new Error("Core não devolveu id da tarefa");
  return id;
}

/**
 * Gera tarefas a partir de pedidos (RPC generate_tasks_from_orders se existir).
 */
export async function generateTasks(restaurantId: string): Promise<void> {
  const { error } = await dockerCoreClient.rpc("generate_tasks_from_orders", {
    p_restaurant_id: restaurantId,
  });
  if (error) throw new Error(error.message ?? "Falha ao gerar tarefas");
}

/**
 * Gera tarefas agendadas (RPC generate_scheduled_tasks se existir).
 */
export async function generateScheduledTasks(restaurantId: string): Promise<void> {
  const { error } = await dockerCoreClient.rpc("generate_scheduled_tasks", {
    p_restaurant_id: restaurantId,
  });
  if (error) throw new Error(error.message ?? "Falha ao gerar tarefas agendadas");
}

/**
 * Reassign task to a different person (or remove assignee).
 */
export async function reassignTask(
  taskId: string,
  assignedTo: string | null,
  assignedName: string | null,
): Promise<void> {
  const { error } = await dockerCoreClient
    .from("gm_tasks")
    .update({ assigned_to: assignedTo, assigned_name: assignedName })
    .eq("id", taskId);
  if (error) throw new Error(error.message ?? "Falha ao reatribuir tarefa");
}

/**
 * Block a task — sets waiting_on in context and optionally changes status.
 * Used when a task can't progress (waiting for ingredient, waiting for table, etc.)
 */
export async function blockTask(
  taskId: string,
  reason: string,
): Promise<void> {
  // First read current context
  const { data: task, error: readErr } = await dockerCoreClient
    .from("gm_tasks")
    .select("context")
    .eq("id", taskId)
    .maybeSingle();

  if (readErr || !task) throw new Error("Task not found");

  const currentContext = (task.context ?? {}) as Record<string, unknown>;
  const updatedContext = {
    ...currentContext,
    waiting_on: reason,
    blocked_at: new Date().toISOString(),
  };

  const { error } = await dockerCoreClient
    .from("gm_tasks")
    .update({ context: updatedContext })
    .eq("id", taskId);

  if (error) throw new Error(error.message ?? "Falha ao bloquear tarefa");
}

/**
 * Unblock a task — removes waiting_on from context.
 */
export async function unblockTask(taskId: string): Promise<void> {
  const { data: task, error: readErr } = await dockerCoreClient
    .from("gm_tasks")
    .select("context")
    .eq("id", taskId)
    .maybeSingle();

  if (readErr || !task) throw new Error("Task not found");

  const currentContext = (task.context ?? {}) as Record<string, unknown>;
  const { waiting_on, blocked_at, ...rest } = currentContext;

  const { error } = await dockerCoreClient
    .from("gm_tasks")
    .update({ context: rest })
    .eq("id", taskId);

  if (error) throw new Error(error.message ?? "Falha ao desbloquear tarefa");
}

/**
 * Add evidence to a task before completing (temperature log, text note, etc.)
 */
export async function addTaskEvidence(
  taskId: string,
  evidence: Record<string, unknown>,
): Promise<void> {
  const { data: task, error: readErr } = await dockerCoreClient
    .from("gm_tasks")
    .select("context")
    .eq("id", taskId)
    .maybeSingle();

  if (readErr || !task) throw new Error("Task not found");

  const currentContext = (task.context ?? {}) as Record<string, unknown>;
  const updatedContext = {
    ...currentContext,
    evidence: {
      ...(currentContext.evidence as Record<string, unknown> ?? {}),
      ...evidence,
      recorded_at: new Date().toISOString(),
    },
  };

  const { error } = await dockerCoreClient
    .from("gm_tasks")
    .update({ context: updatedContext })
    .eq("id", taskId);

  if (error) throw new Error(error.message ?? "Falha ao adicionar evidência");
}

/**
 * Resolve task with evidence in one operation.
 */
export async function resolveTaskWithEvidence(
  taskId: string,
  evidence?: Record<string, unknown>,
): Promise<void> {
  if (evidence) {
    await addTaskEvidence(taskId, evidence);
  }
  await resolveTask(taskId);
}

/**
 * Escalate task priority (e.g. MEDIA -> ALTA -> CRITICA).
 */
export async function escalateTask(taskId: string): Promise<void> {
  const { data: task, error: readErr } = await dockerCoreClient
    .from("gm_tasks")
    .select("priority")
    .eq("id", taskId)
    .maybeSingle();

  if (readErr || !task) throw new Error("Task not found");

  const ESCALATION: Record<string, string> = {
    BAIXA: "MEDIA",
    LOW: "MEDIA",
    MEDIA: "ALTA",
    ALTA: "CRITICA",
    CRITICA: "CRITICA",
  };

  const newPriority = ESCALATION[task.priority ?? "MEDIA"] ?? "ALTA";

  const { error } = await dockerCoreClient
    .from("gm_tasks")
    .update({ priority: newPriority })
    .eq("id", taskId);

  if (error) throw new Error(error.message ?? "Failed to escalate task");
}
