import { DeliveryOrder } from '../delivery-integration-service';

/**
 * iFood Adapter
 * Handles communication with iFood API v1.0
 */
export class IfoodAdapter {
    private baseUrl = 'https://merchant-api.ifood.com.br/order/v1.0';

    constructor(
        private token: string
    ) { }

    /**
     * Poll for new events
     * GET /events:polling
     */
    async poll(): Promise<any[]> {
        // STUB: In production, fetch from API
        // const response = await fetch(`${this.baseUrl}/events:polling`, { ... });
        // return response.json();

        console.log('[IfoodAdapter] Polling events...');
        return []; // Return empty for now to avoid errors
    }

    /**
     * Acknowledge events
     * POST /events/acknowledgment
     */
    async acknowledge(events: any[]): Promise<void> {
        if (events.length === 0) return;

        console.log('[IfoodAdapter] Acknowledging events:', events.map(e => e.id));
        // STUB: Call API
    }

    /**
     * Fetch full order details
     * GET /orders/{id}
     */
    async fetchOrder(orderId: string): Promise<any> {
        // STUB: Mock Order
        return {
            id: orderId,
            displayId: '1234',
            createdAt: new Date().toISOString(),
            customer: {
                name: 'Cliente iFood Teste',
                phone: { number: '11999999999' }
            },
            items: [
                { name: 'Hambúrguer', quantity: 1, price: 25.00 },
                { name: 'Coca-Cola', quantity: 2, price: 5.00 }
            ],
            total: {
                orderAmount: 35.00
            },
            delivery: {
                deliveryAddress: {
                    formattedAddress: 'Rua Teste, 123'
                }
            }
        };
    }

    /**
     * Map iFood order to internal format
     */
    mapToInternal(ifoodOrder: any): DeliveryOrder {
        return {
            id: '', // Will be generated by DB
            channel: 'ifood',
            external_order_id: ifoodOrder.id,
            customer_name: ifoodOrder.customer.name,
            customer_phone: ifoodOrder.customer.phone.number,
            delivery_address: ifoodOrder.delivery?.deliveryAddress?.formattedAddress || 'Retirada',
            items: ifoodOrder.items.map((item: any) => ({
                product_name: item.name,
                quantity: item.quantity,
                price: item.price
            })),
            total: ifoodOrder.total.orderAmount,
            status: 'pending',
            created_at: ifoodOrder.createdAt
        };
    }
}
