import { DeliveryOrder } from '../delivery-integration-service';

/**
 * Uber Eats Adapter
 * Handles communication with Uber Eats API
 */
export class UberEatsAdapter {
    private baseUrl = 'https://api.uber.com/v2/eats';

    constructor(
        private token: string
    ) {}

    /**
     * Poll for new events / orders
     * Note: Uber Eats usually pushes, but we poll 'created' orders for this adapter pattern.
     */
    async poll(): Promise<any[]> {
        console.log('[UberEatsAdapter] Polling orders...');
        return []; // Return empty stub
    }

    /**
     * Fetch full order details
     */
    async fetchOrder(orderId: string): Promise<any> {
        // STUB: Mock Order
        return {
            id: orderId,
            display_id: 'UB888',
            created_time: new Date().getTime(),
            eater: {
                first_name: 'Uber',
                last_name: 'Tester',
                phone: '+5511988888888'
            },
            cart: {
                items: [
                    { title: 'Taco', quantity: 3, price: { amount: 1500 } }
                ]
            },
            payment: {
                amount: { amount: 4500 }, // in cents
            },
            delivery: {
                location: {
                    address: 'Avenida Paulista, 1000'
                }
            }
        };
    }

    /**
     * Map Uber order to internal format
     */
    mapToInternal(uberOrder: any): DeliveryOrder {
        return {
            id: '', // Will be generated by DB
            channel: 'uber_eats',
            external_order_id: uberOrder.id,
            customer_name: `${uberOrder.eater.first_name} ${uberOrder.eater.last_name}`,
            customer_phone: uberOrder.eater.phone,
            delivery_address: uberOrder.delivery?.location?.address || 'Retirada',
            items: uberOrder.cart.items.map((item: any) => ({
                product_name: item.title,
                quantity: item.quantity,
                price: item.price.amount / 100 // Convert cents to units if needed by interface, but logic usually expects internal cents? Interface says number. Assuming cents/100 based on previous iFood. Wait, DeliveryOrder interface says price: number. Usually cents is safer. Let's check interface.
                // Checking previous code... typical JS floats.
            })),
            total: uberOrder.payment.amount.amount / 100, // Total
            status: 'pending',
            created_at: new Date(uberOrder.created_time).toISOString()
        };
    }
}
