/**
 * Inventory Lite — alertas de stock (esgotou) e criação de tarefa "Repor X".
 * Conforme TASKS_CONTRACT_v1 (ESTOQUE_CRITICO), ERROS_CANON E56–E60.
 */

import React, { useState } from "react";
import { createTaskRpc } from "../../../infra/writers/TaskWriter";
import { useToast } from "../../../ui/design-system";
import { Button } from "../../../ui/design-system/Button";
import { Card } from "../../../ui/design-system/Card";
import { Text } from "../../../ui/design-system/primitives/Text";
import { useAppStaffPermissions } from "../hooks/useAppStaffPermissions";
import { useStockAlerts } from "../hooks/useStockAlerts";

export interface InventoryLiteSectionProps {
  restaurantId: string | undefined | null;
}

export const InventoryLiteSection: React.FC<InventoryLiteSectionProps> = ({
  restaurantId,
}) => {
  const { alerts, loading, error, refresh } = useStockAlerts(restaurantId);
  const perms = useAppStaffPermissions();
  const { success, error: toastError } = useToast();
  const [busy, setBusy] = useState<Record<string, boolean>>({});

  const handleCreateReporTask = async (
    ingredientName: string,
    ingredientId: string,
    locationId: string
  ) => {
    if (!restaurantId || !perms.canCreateTask) return;
    const key = `${ingredientId}-${locationId}`;
    setBusy((b) => ({ ...b, [key]: true }));
    try {
      await createTaskRpc({
        restaurantId,
        taskType: "ESTOQUE_CRITICO",
        message: `Repor ${ingredientName}`,
        priority: "ALTA",
        context: { ingredient_id: ingredientId, location_id: locationId },
        autoGenerated: false,
      });
      success(`Tarefa "Repor ${ingredientName}" criada`);
      await refresh();
    } catch (e) {
      toastError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy((b) => ({ ...b, [key]: false }));
    }
  };

  if (!perms.canSeeInventoryLite) return null;

  if (loading) {
    return (
      <Card surface="layer2" padding="md">
        <Text size="sm" color="tertiary">
          A carregar estoque...
        </Text>
      </Card>
    );
  }

  if (error) {
    return (
      <Card
        surface="layer2"
        padding="md"
        style={{ borderLeft: "4px solid var(--color-destructive, #ef4444)" }}
      >
        <Text size="sm" color="primary">
          {error}
        </Text>
        <Button
          size="sm"
          tone="neutral"
          style={{ marginTop: 8 }}
          onClick={refresh}
        >
          Retry
        </Button>
      </Card>
    );
  }

  if (alerts.length === 0) {
    return (
      <Card surface="layer2" padding="md">
        <Text
          size="xs"
          weight="bold"
          color="tertiary"
          style={{ textTransform: "uppercase", letterSpacing: 1 }}
        >
          Estoque
        </Text>
        <Text size="sm" color="tertiary" style={{ marginTop: 8 }}>
          Nenhum alerta de stock (todos acima do mínimo).
        </Text>
      </Card>
    );
  }

  return (
    <Card
      surface="layer2"
      padding="md"
      style={{ display: "flex", flexDirection: "column", gap: 12 }}
    >
      <Text
        size="xs"
        weight="bold"
        color="tertiary"
        style={{ textTransform: "uppercase", letterSpacing: 1 }}
      >
        Estoque — Repor
      </Text>
      <Text size="sm" color="secondary" style={{ marginBottom: 4 }}>
        Abaixo do mínimo ({alerts.length})
      </Text>
      <ul
        style={{
          listStyle: "none",
          padding: 0,
          margin: 0,
          display: "flex",
          flexDirection: "column",
          gap: 8,
        }}
      >
        {alerts.map((a) => {
          const key = `${a.ingredient_id}-${a.location_id}`;
          const name = a.ingredient?.name ?? "Ingrediente";
          const locationName = a.location?.name ?? "Local";
          return (
            <li
              key={a.id}
              style={{
                padding: 10,
                background: "var(--color-surface-layer3, #1a1a1a)",
                borderRadius: 8,
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                flexWrap: "wrap",
                gap: 8,
              }}
            >
              <div>
                <Text size="sm" weight="bold">
                  {name}
                </Text>
                <Text size="xs" color="tertiary">
                  {locationName} · {a.qty} / {a.min_qty}{" "}
                  {a.ingredient?.unit ?? ""}
                </Text>
              </div>
              {perms.canCreateTask && (
                <Button
                  size="sm"
                  tone="action"
                  disabled={busy[key]}
                  onClick={() =>
                    handleCreateReporTask(name, a.ingredient_id, a.location_id)
                  }
                >
                  Criar tarefa repor
                </Button>
              )}
            </li>
          );
        })}
      </ul>
      <Button size="sm" tone="neutral" variant="outline" onClick={refresh}>
        Actualizar
      </Button>
    </Card>
  );
};
