/**
 * ShiftTaskMaterializer — Materializa templates de role como tarefas reais em gm_tasks.
 *
 * Chamado no check-in do operador. Idempotente: verifica se a tarefa
 * ja existe hoje (por template_key + date) antes de criar.
 */

import { dockerCoreClient } from "../../infra/docker-core/connection";
import { createTaskRpc } from "../../infra/writers/TaskWriter";
import {
  getTemplatesForRole,
  type RoleTaskTemplate,
} from "../../pages/AppStaff/data/roleTaskTemplates";
import type { StaffRole } from "../../pages/AppStaff/context/StaffCoreTypes";

// ---------------------------------------------------------------------------
// Priority mapping: template priority -> gm_tasks priority
// ---------------------------------------------------------------------------

const PRIORITY_MAP: Record<string, string> = {
  critical: "CRITICA",
  high: "ALTA",
  normal: "MEDIA",
  low: "BAIXA",
};

// ---------------------------------------------------------------------------
// Role -> station mapping (mirrors StaffContext:98)
// ---------------------------------------------------------------------------

function mapRoleToStation(role: StaffRole): string {
  switch (role) {
    case "kitchen":
      return "KITCHEN";
    case "waiter":
      return "SERVICE";
    case "cleaning":
      return "SERVICE";
    case "delivery":
      return "SERVICE";
    case "manager":
      return "SERVICE";
    case "owner":
      return "SERVICE";
    case "worker":
      return "SERVICE";
    default:
      return "SERVICE";
  }
}

// ---------------------------------------------------------------------------
// Today helper
// ---------------------------------------------------------------------------

function getToday(): string {
  return new Date().toISOString().slice(0, 10); // "2026-03-18"
}

// ---------------------------------------------------------------------------
// Main function
// ---------------------------------------------------------------------------

/**
 * Materializa tarefas de turno para um role num restaurante.
 * Idempotente: nao cria duplicados para o mesmo dia.
 *
 * @returns Array de IDs das tarefas criadas (vazio se todas ja existiam)
 */
export async function materializeShiftTasks(
  restaurantId: string,
  role: StaffRole,
  moment?: "opening" | "during_service" | "closing" | "anytime",
): Promise<string[]> {
  const today = getToday();

  // 1. Get templates for the role, filtered by moment
  let templates = getTemplatesForRole(role);
  if (moment) {
    templates = templates.filter(
      (t) => t.moment === moment || t.moment === "anytime",
    );
  }

  if (templates.length === 0) return [];

  // 2. Query existing shift tasks for today (avoid duplicates)
  const templateKeys = templates.map((t) => t.key);
  const { data: existingTasks } = await dockerCoreClient
    .from("gm_tasks")
    .select("id, context")
    .eq("restaurant_id", restaurantId)
    .eq("task_type", "SHIFT_CHECKLIST")
    .not("status", "eq", "DISMISSED");

  // Build set of template_keys that already have a task today
  const existingKeys = new Set<string>();
  for (const task of existingTasks ?? []) {
    const ctx = (task.context ?? {}) as Record<string, unknown>;
    if (ctx.template_key && ctx.date === today) {
      existingKeys.add(ctx.template_key as string);
    }
  }

  // 3. Create missing tasks
  const templatesToCreate = templates.filter(
    (t) => !existingKeys.has(t.key),
  );

  if (templatesToCreate.length === 0) return [];

  const createdIds: string[] = [];

  for (const template of templatesToCreate) {
    try {
      const id = await createTaskRpc({
        restaurantId,
        taskType: "SHIFT_CHECKLIST",
        message: template.title,
        priority: PRIORITY_MAP[template.priority] ?? "MEDIA",
        station: mapRoleToStation(role),
        context: {
          template_key: template.key,
          template_category: template.category,
          template_icon: template.icon,
          template_mandatory: template.mandatory ?? false,
          required_evidence: template.requiresEvidence ?? null,
          estimated_minutes: template.estimatedMinutes,
          template_moment: template.moment ?? "anytime",
          date: today,
        },
        autoGenerated: true,
      });
      createdIds.push(id);
    } catch (err) {
      console.error(
        `[ShiftTaskMaterializer] Failed to create task for ${template.key}:`,
        err,
      );
    }
  }

  return createdIds;
}
