-- v1.1 Operational Layer: Staff Tasks & Shifts
-- Date: 2025-12-26
-- 1. Staff Shifts (Turnos)
create table if not exists staff_shifts (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null,
    -- references restaurant_web_profiles(restaurant_id)
    worker_name text not null,
    -- simplified for now (no auth_user_id yet)
    role text not null check (
        role in ('garcom', 'cozinheiro', 'gerente', 'dono')
    ),
    status text not null default 'pending' check (
        status in ('pending', 'active', 'completed', 'absent')
    ),
    start_time timestamptz,
    end_time timestamptz,
    risk_level text default 'low' check (risk_level in ('low', 'medium', 'high')),
    compliance_status text default 'ok' check (compliance_status in ('ok', 'warning', 'alert')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists idx_staff_shifts_restaurant on staff_shifts(restaurant_id, created_at desc);
create index if not exists idx_staff_shifts_status on staff_shifts(status);
-- 2. Staff Tasks (Tarefas)
create table if not exists staff_tasks (
    id uuid primary key default gen_random_uuid(),
    restaurant_id uuid not null,
    -- references restaurant_web_profiles(restaurant_id)
    title text not null,
    description text,
    status text not null default 'pending' check (
        status in ('pending', 'in-progress', 'completed', 'overdue')
    ),
    priority text not null default 'medium' check (priority in ('low', 'medium', 'critical')),
    assigned_to text,
    -- worker name or role (e.g. 'kitchen')
    due_at timestamptz,
    requires_validation boolean default false,
    validated_by text,
    origin_event_id uuid,
    -- e.g. references web_orders(id)
    origin_type text,
    -- 'ORDER', 'HACCP', 'SYSTEM'
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists idx_staff_tasks_restaurant on staff_tasks(restaurant_id, status);
create index if not exists idx_staff_tasks_assigned on staff_tasks(assigned_to);
-- 3. Comments
comment on table staff_shifts is 'Operational shifts for staff (Waiter/Cook/Manager)';
comment on table staff_tasks is 'Operational tasks generated by TPV events or schedules';