/**
 * seed-demo-reviews.ts — Seed de 40 Reviews Demo para Local Boss
 * Cobre 6 temas com sentimentos mistos, incluindo casos de nomes de garçons.
 */

import { IngestReview } from './ingest';

export const DEMO_REVIEWS: IngestReview[] = [
  // === SERVICE (Atendimento) ===
  {
    source: 'google',
    review_id: 'demo-service-1',
    rating: 5,
    author: 'Maria Silva',
    text: 'Excelente atendimento! O garçom João foi muito atencioso e prestativo. Recomendo!',
    published_at: new Date().toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-service-2',
    rating: 2,
    author: 'Carlos Santos',
    text: 'Atendimento ruim. O garçom demorou muito e foi mal educado. Não voltarei.',
    published_at: new Date(Date.now() - 86400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-service-3',
    rating: 4,
    author: 'Ana Costa',
    text: 'Bom atendimento, mas poderia ser mais rápido. A equipe foi educada.',
    published_at: new Date(Date.now() - 172800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-service-4',
    rating: 1,
    author: 'Pedro Lima',
    text: 'Péssimo! O garçom Maria ignorou nossos pedidos várias vezes. Muito desatento.',
    published_at: new Date(Date.now() - 259200000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-service-5',
    rating: 5,
    author: 'Julia Ferreira',
    text: 'Atendimento impecável! Muito atencioso e eficiente. Parabéns à equipe!',
    published_at: new Date(Date.now() - 345600000).toISOString(),
    language: 'pt',
  },

  // === CLEANLINESS (Limpeza) ===
  {
    source: 'google',
    review_id: 'demo-clean-1',
    rating: 5,
    author: 'Roberto Alves',
    text: 'Restaurante muito limpo e organizado. Higiene impecável!',
    published_at: new Date(Date.now() - 432000000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-clean-2',
    rating: 2,
    author: 'Fernanda Rocha',
    text: 'Mesa suja quando chegamos. Banheiro mal cuidado. Precisa melhorar a limpeza.',
    published_at: new Date(Date.now() - 518400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-clean-3',
    rating: 4,
    author: 'Lucas Martins',
    text: 'Ambiente limpo e bem cuidado. Bem organizado.',
    published_at: new Date(Date.now() - 604800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-clean-4',
    rating: 3,
    author: 'Patricia Souza',
    text: 'Limpeza ok, mas poderia ser melhor. Alguns cantos com poeira.',
    published_at: new Date(Date.now() - 691200000).toISOString(),
    language: 'pt',
  },

  // === PRICE (Preço) ===
  {
    source: 'google',
    review_id: 'demo-price-1',
    rating: 4,
    author: 'Ricardo Oliveira',
    text: 'Preço justo para a qualidade. Vale a pena!',
    published_at: new Date(Date.now() - 777600000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-price-2',
    rating: 2,
    author: 'Sandra Costa',
    text: 'Muito caro para o que oferece. Não vale o preço. Complicado de usar o sistema.',
    published_at: new Date(Date.now() - 864000000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-price-3',
    rating: 5,
    author: 'Marcos Silva',
    text: 'Excelente custo-benefício! Preço razoável e comida ótima.',
    published_at: new Date(Date.now() - 950400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-price-4',
    rating: 1,
    author: 'Beatriz Lima',
    text: 'Caro demais! Muito dinheiro para pouco resultado. Não resolveu minha expectativa.',
    published_at: new Date(Date.now() - 1036800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-price-5',
    rating: 3,
    author: 'Thiago Santos',
    text: 'Preço ok, mas comparado com outros lugares, está um pouco alto.',
    published_at: new Date(Date.now() - 1123200000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-price-6',
    rating: 2,
    author: 'Camila Rocha',
    text: 'Sistema confuso e não funciona direito. Por esse preço, esperava mais.',
    published_at: new Date(Date.now() - 1209600000).toISOString(),
    language: 'pt',
  },

  // === PRODUCT (Produto/Comida) ===
  {
    source: 'google',
    review_id: 'demo-product-1',
    rating: 5,
    author: 'Gabriel Alves',
    text: 'Comida deliciosa! Saboroso e bem feito. Perfeito!',
    published_at: new Date(Date.now() - 1296000000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-product-2',
    rating: 2,
    author: 'Isabela Ferreira',
    text: 'Comida sem sabor. Prato chegou frio. Qualidade ruim.',
    published_at: new Date(Date.now() - 1382400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-product-3',
    rating: 4,
    author: 'Rafael Martins',
    text: 'Bom sabor, comida bem preparada. Recomendo!',
    published_at: new Date(Date.now() - 1468800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-product-4',
    rating: 1,
    author: 'Larissa Souza',
    text: 'Comida queimada e sem qualidade. Péssimo!',
    published_at: new Date(Date.now() - 1555200000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-product-5',
    rating: 5,
    author: 'Bruno Oliveira',
    text: 'Excelente comida! Sabor incrível e pratos bem apresentados.',
    published_at: new Date(Date.now() - 1641600000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-product-6',
    rating: 3,
    author: 'Amanda Costa',
    text: 'Comida ok, mas nada especial. Esperava mais pelo preço.',
    published_at: new Date(Date.now() - 1728000000).toISOString(),
    language: 'pt',
  },

  // === AMBIANCE (Ambiente) ===
  {
    source: 'google',
    review_id: 'demo-ambiance-1',
    rating: 5,
    author: 'Felipe Rocha',
    text: 'Ambiente agradável e aconchegante. Muito bonito!',
    published_at: new Date(Date.now() - 1814400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-ambiance-2',
    rating: 2,
    author: 'Carolina Lima',
    text: 'Muito barulhento e desconfortável. Ambiente ruim.',
    published_at: new Date(Date.now() - 1900800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-ambiance-3',
    rating: 4,
    author: 'Gustavo Silva',
    text: 'Bom ambiente, confortável e bem decorado.',
    published_at: new Date(Date.now() - 1987200000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-ambiance-4',
    rating: 3,
    author: 'Renata Alves',
    text: 'Ambiente ok, mas poderia ser mais aconchegante.',
    published_at: new Date(Date.now() - 2073600000).toISOString(),
    language: 'pt',
  },

  // === WAIT_TIME (Tempo de Espera) ===
  {
    source: 'google',
    review_id: 'demo-wait-1',
    rating: 5,
    author: 'Daniel Ferreira',
    text: 'Atendimento rápido! Sem espera. Muito eficiente!',
    published_at: new Date(Date.now() - 2160000000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-wait-2',
    rating: 1,
    author: 'Vanessa Santos',
    text: 'Demorou muito! Espera de mais de 1 hora. Muito lento.',
    published_at: new Date(Date.now() - 2246400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-wait-3',
    rating: 3,
    author: 'André Martins',
    text: 'Espera um pouco longa, mas a comida compensa.',
    published_at: new Date(Date.now() - 2332800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-wait-4',
    rating: 2,
    author: 'Juliana Rocha',
    text: 'Muito atraso. Pedido demorou demais para chegar. Péssimo!',
    published_at: new Date(Date.now() - 2419200000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-wait-5',
    rating: 4,
    author: 'Rodrigo Lima',
    text: 'Rápido e eficiente. Sem demora no atendimento.',
    published_at: new Date(Date.now() - 2505600000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-wait-6',
    rating: 1,
    author: 'Tatiana Costa',
    text: 'Espera muito longa. Muito tempo até o pedido chegar. Não recomendo.',
    published_at: new Date(Date.now() - 2592000000).toISOString(),
    language: 'pt',
  },

  // === MIXED (Múltiplos Temas) ===
  {
    source: 'google',
    review_id: 'demo-mixed-1',
    rating: 4,
    author: 'Leonardo Souza',
    text: 'Bom atendimento, comida deliciosa, mas demorou um pouco. Preço justo.',
    published_at: new Date(Date.now() - 2678400000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-mixed-2',
    rating: 2,
    author: 'Priscila Alves',
    text: 'Atendimento ruim, comida fria, muito caro e demorou muito. Não voltarei.',
    published_at: new Date(Date.now() - 2764800000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-mixed-3',
    rating: 5,
    author: 'Eduardo Ferreira',
    text: 'Excelente! Atendimento rápido, comida deliciosa, ambiente agradável e preço justo.',
    published_at: new Date(Date.now() - 2851200000).toISOString(),
    language: 'pt',
  },
  {
    source: 'google',
    review_id: 'demo-mixed-4',
    rating: 3,
    author: 'Mariana Santos',
    text: 'Comida boa, mas atendimento lento e ambiente barulhento. Preço ok.',
    published_at: new Date(Date.now() - 2937600000).toISOString(),
    language: 'pt',
  },
];

