-- Migration: Performance Indexes
-- Description: Adds covering indexes for unindexed foreign keys identified by Database Linter
-- Date: 2026-01-09
-- 1. app_logs
-- CREATE INDEX IF NOT EXISTS idx_app_logs_restaurant_id ON public.app_logs(restaurant_id);
-- 2. app_tasks
-- CREATE INDEX IF NOT EXISTS idx_app_tasks_assigned_to ON public.app_tasks(assigned_to);
-- CREATE INDEX IF NOT EXISTS idx_app_tasks_created_by ON public.app_tasks(created_by);
-- CREATE INDEX IF NOT EXISTS idx_app_tasks_restaurant_id ON public.app_tasks(restaurant_id);
-- 3. campaign_placements
-- CREATE INDEX IF NOT EXISTS idx_campaign_placements_campaign_id ON public.campaign_placements(campaign_id);
-- 4. campaigns
-- CREATE INDEX IF NOT EXISTS idx_campaigns_supplier_id ON public.campaigns(supplier_id);
-- 5. cases
-- CREATE INDEX IF NOT EXISTS idx_cases_assigned_to ON public.cases(assigned_to);
-- CREATE INDEX IF NOT EXISTS idx_cases_created_by ON public.cases(created_by);
-- CREATE INDEX IF NOT EXISTS idx_cases_workspace_id ON public.cases(workspace_id);
-- 6. cash_registers
-- CREATE INDEX IF NOT EXISTS idx_cash_registers_closed_by ON public.cash_registers(closed_by);
-- CREATE INDEX IF NOT EXISTS idx_cash_registers_opened_by ON public.cash_registers(opened_by);
-- 7. devices
-- CREATE INDEX IF NOT EXISTS idx_devices_user_id ON public.devices(user_id);
-- 8. empire_pulses
-- CREATE INDEX IF NOT EXISTS idx_empire_pulses_restaurant_id ON public.empire_pulses(restaurant_id);
-- 9. employees
-- CREATE INDEX IF NOT EXISTS idx_employees_profile_id ON public.employees(profile_id);
-- CREATE INDEX IF NOT EXISTS idx_employees_restaurant_id ON public.employees(restaurant_id);
-- 10. events
-- CREATE INDEX IF NOT EXISTS idx_events_actor_id ON public.events(actor_id);
-- CREATE INDEX IF NOT EXISTS idx_events_workspace_id ON public.events(workspace_id);
-- 11. evidence
-- CREATE INDEX IF NOT EXISTS idx_evidence_uploaded_by ON public.evidence(uploaded_by);
-- 12. gm_daily_closings
-- CREATE INDEX IF NOT EXISTS idx_gm_daily_closings_created_by ON public.gm_daily_closings(created_by);
-- 13. gm_diagnostics
-- CREATE INDEX IF NOT EXISTS idx_gm_diagnostics_tenant_id ON public.gm_diagnostics(tenant_id);
-- CREATE INDEX IF NOT EXISTS idx_gm_diagnostics_user_id ON public.gm_diagnostics(user_id);
-- 14. gm_inventory_items
-- CREATE INDEX IF NOT EXISTS idx_gm_inventory_items_restaurant_id ON public.gm_inventory_items(restaurant_id);
-- 15. gm_inventory_levels
-- CREATE INDEX IF NOT EXISTS idx_gm_inventory_levels_link_id ON public.gm_inventory_levels(link_id);
-- CREATE INDEX IF NOT EXISTS idx_gm_inventory_levels_restaurant_id ON public.gm_inventory_levels(restaurant_id);
-- 16. gm_inventory_links
-- CREATE INDEX IF NOT EXISTS idx_gm_inventory_links_organ_id ON public.gm_inventory_links(organ_id);
-- CREATE INDEX IF NOT EXISTS idx_gm_inventory_links_restaurant_id ON public.gm_inventory_links(restaurant_id);
-- 17. gm_orders
CREATE INDEX IF NOT EXISTS idx_gm_orders_operator_id ON public.gm_orders(operator_id);
-- 18. gm_organs
-- CREATE INDEX IF NOT EXISTS idx_gm_organs_restaurant_id ON public.gm_organs(restaurant_id);
-- 19. gm_products
CREATE INDEX IF NOT EXISTS idx_gm_products_restaurant_id ON public.gm_products(restaurant_id);
-- 20. gm_tables
CREATE INDEX IF NOT EXISTS idx_gm_tables_restaurant_id ON public.gm_tables(restaurant_id);
-- 21. gm_task_events
-- CREATE INDEX IF NOT EXISTS idx_gm_task_events_restaurant_id ON public.gm_task_events(restaurant_id);
-- 22. projects (GHOST TABLE)
-- CREATE INDEX IF NOT EXISTS idx_projects_workspace_id ON public.projects(workspace_id);
-- 23. restaurant_members
-- CREATE INDEX IF NOT EXISTS idx_restaurant_members_restaurant_id ON public.restaurant_members(restaurant_id);
-- CREATE INDEX IF NOT EXISTS idx_restaurant_members_user_id ON public.restaurant_members(user_id);
-- 24. restaurants
-- CREATE INDEX IF NOT EXISTS idx_restaurants_owner_id ON public.restaurants(owner_id);
-- 25. web_order_items
-- CREATE INDEX IF NOT EXISTS idx_web_order_items_menu_item_id ON public.web_order_items(menu_item_id);
-- 26. workspace_members
-- CREATE INDEX IF NOT EXISTS idx_workspace_members_user_id ON public.workspace_members(user_id);;
-- Migration: Add Sovereign Columns to gm_restaurants
-- Generated by Antigravity to fix Schema Mismatch in Onboarding 2.0
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS evidence JSONB;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS onboarding_level TEXT;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS modules_unlocked JSONB;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS topology JSONB;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS flow_type TEXT;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS finance JSONB;;
-- Migration: 20260110000001_operation_status_audit.sql
-- Purpose: Create audit table for operation status changes (Opus 6.0)
-- Date: 2026-01-10
-- Create ENUM for operation status if it doesn't exist
DO $$ BEGIN CREATE TYPE operation_status AS ENUM ('active', 'paused', 'suspended');
EXCEPTION
WHEN duplicate_object THEN null;
END $$;
-- ============================================================
-- 1) CREATE AUDIT TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.operation_status_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    restaurant_id UUID NOT NULL REFERENCES public.gm_restaurants(id) ON DELETE CASCADE,
    previous_status operation_status,
    new_status operation_status NOT NULL,
    reason TEXT,
    actor_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (now() at time zone 'utc')
);
-- ============================================================
-- 2) CREATE INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_operation_status_audit_restaurant ON public.operation_status_audit(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_operation_status_audit_created_at ON public.operation_status_audit(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_operation_status_audit_status ON public.operation_status_audit(new_status);
-- ============================================================
-- 3) UPDATE FUNCTION TO LOG AUDIT
-- ============================================================
CREATE OR REPLACE FUNCTION update_operation_status(
        p_restaurant_id UUID,
        p_status operation_status,
        p_reason TEXT DEFAULT NULL,
        p_actor_id UUID DEFAULT NULL
    ) RETURNS VOID AS $$
DECLARE v_previous_status operation_status;
v_metadata JSONB;
BEGIN -- Get current status and metadata
SELECT operation_status,
    operation_metadata INTO v_previous_status,
    v_metadata
FROM gm_restaurants
WHERE id = p_restaurant_id;
-- If status hasn't changed, do nothing
IF v_previous_status = p_status THEN RETURN;
END IF;
-- Log to audit table
INSERT INTO public.operation_status_audit (
        restaurant_id,
        previous_status,
        new_status,
        reason,
        actor_id
    )
VALUES (
        p_restaurant_id,
        v_previous_status,
        p_status,
        p_reason,
        p_actor_id
    );
-- Update metadata with audit trail
v_metadata := COALESCE(v_metadata, '{}'::jsonb) || jsonb_build_object(
    'last_update',
    (now() at time zone 'utc'),
    'reason',
    p_reason,
    'updated_by',
    p_actor_id,
    'previous_status',
    v_previous_status
);
-- Perform update
UPDATE gm_restaurants
SET operation_status = p_status,
    operation_metadata = v_metadata,
    updated_at = (now() at time zone 'utc')
WHERE id = p_restaurant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- ============================================================
-- 4) RLS POLICIES
-- ============================================================
ALTER TABLE public.operation_status_audit ENABLE ROW LEVEL SECURITY;
-- Users can only see audit logs for restaurants they have access to
CREATE POLICY "Users can view operation status audit for their restaurants" ON public.operation_status_audit FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.restaurant_members
            WHERE restaurant_id = operation_status_audit.restaurant_id
                AND user_id = auth.uid()
        )
    );
-- Only system can insert (via function)
CREATE POLICY "Only system can insert operation status audit" ON public.operation_status_audit FOR
INSERT WITH CHECK (false);
-- Function uses SECURITY DEFINER
-- ============================================================
-- 5) HELPER FUNCTION: Get Operation History
-- ============================================================
CREATE OR REPLACE FUNCTION get_operation_status_history(
        p_restaurant_id UUID,
        p_limit INTEGER DEFAULT 50
    ) RETURNS TABLE (
        id UUID,
        previous_status operation_status,
        new_status operation_status,
        reason TEXT,
        actor_id UUID,
        created_at TIMESTAMPTZ
    ) LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN RETURN QUERY
SELECT osa.id,
    osa.previous_status,
    osa.new_status,
    osa.reason,
    osa.actor_id,
    osa.created_at
FROM public.operation_status_audit osa
WHERE osa.restaurant_id = p_restaurant_id
ORDER BY osa.created_at DESC
LIMIT p_limit;
END;
$$;
-- ============================================================
-- 6) COMMENTS
-- ============================================================
COMMENT ON TABLE public.operation_status_audit IS 'Audit log for operation status changes (Opus 6.0)';
COMMENT ON FUNCTION update_operation_status IS 'Updates operation status and logs to audit table';
COMMENT ON FUNCTION get_operation_status_history IS 'Returns operation status change history for a restaurant';;
