-- Migration: Add Sovereign Columns to gm_restaurants
-- Generated by Antigravity to fix Schema Mismatch in Onboarding 2.0
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS evidence JSONB;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS onboarding_level TEXT;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS modules_unlocked JSONB;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS topology JSONB;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS flow_type TEXT;
ALTER TABLE gm_restaurants
ADD COLUMN IF NOT EXISTS finance JSONB;