CREATE TABLE IF NOT EXISTS public.gm_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  table_id uuid,
  table_number integer,
  status text NOT NULL DEFAULT 'OPEN'::text,
  payment_status text NOT NULL DEFAULT 'PENDING'::text,
  total_cents integer DEFAULT 0,
  subtotal_cents integer DEFAULT 0,
  tax_cents integer DEFAULT 0,
  discount_cents integer DEFAULT 0,
  source text DEFAULT 'tpv'::text,
  operator_id uuid,
  cash_register_id uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  sync_metadata jsonb,
  origin text,
  in_prep_at timestamp with time zone,
  ready_at timestamp with time zone,
  served_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);
